In [1]:
import numpy as np
import pandas as pd

In [3]:
data=pd.read_excel('DataCUSAAssgn1.xls')

In [4]:
data.head()

,Srl No,V1 - I plan my expenses…,V2 - I always use new brands…,V3 - Weekends at home with family…,V4 - Buy more by impulse while shopping…,V5 - Watch online rather than TV shows,"V6 - Prefer reading, music rather than sports wctivities",V7 - Watch movies in first few days of release,V8 - I order for everyone while eating out,V9 - Some physical exercise everyday,...,Q2 - Mobile Phn Brand,Q3 - Favourite Soft Drink,Q4 - Newspaper read,Q5 - Shower Gel,Q6 - Hand sanitizers,Q7 - Face washes,Q8 - Hair conditioner,Q9 - Tea_Coffee,Q10 - Gender,Q11 - Occupation
0,1,4,9,4,6,9,8,9,8,8,...,Samsung,Cola,Economic Times,3,4,4,3,1,1,1
1,2,9,6,9,1,5,9,8,8,9,...,Others,Orange,The Hindu,1,2,2,3,1,1,1
2,3,4,6,5,7,6,5,0,5,3,...,HTC,Fruit flavour,Times of India,2,3,4,3,2,1,1
3,4,6,9,5,10,10,5,6,5,4,...,Others,I do not consume soft drinks at all,The Hindu,3,3,4,3,1,2,1
4,5,8,1,9,7,8,9,1,1,7,...,Others,Fruit flavour,Economic Times,2,3,2,2,1,1,1

In [7]:
data1=data.iloc[:,1:16]

In [8]:
data1.head()

,V1 - I plan my expenses…,V2 - I always use new brands…,V3 - Weekends at home with family…,V4 - Buy more by impulse while shopping…,V5 - Watch online rather than TV shows,"V6 - Prefer reading, music rather than sports wctivities",V7 - Watch movies in first few days of release,V8 - I order for everyone while eating out,V9 - Some physical exercise everyday,"V10 - Prefer light, sober colours","V11 - I discuss my problem, rather than keeping them to myself",V12 - I like performing on a stage in front of a huge crowd,"V13 - At parties, I like mingling with new people rather than sticking to my close circle",V14 - Math Science were my favourite subjects in school,"V15 - When I see a new, interesting ad I most often end up buying the brand"
0,4,9,4,6,9,8,9,8,8,8,8,4,6,7,7
1,9,6,9,1,5,9,8,8,9,5,2,8,1,8,2
2,4,6,5,7,6,5,0,5,3,7,0,4,3,7,3
3,6,9,5,10,10,5,6,5,4,6,5,7,6,10,6
4,8,1,9,7,8,9,1,1,7,9,6,1,7,8,2

In [9]:
data1.shape

(400, 15)

In [17]:
data2=data1.astype(object)
data2=pd.get_dummies(data2)

In [19]:
data2.shape

(400, 165)

In [10]:
from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans

In [29]:
sil=[]
sumsquare=[]
for i in range(3,6):
    kmeans = KMeans(n_clusters=i, random_state=0).fit(data1)
    sil.append(silhouette_score(data1,kmeans.labels_))
    sumsquare.append(kmeans.inertia_)

In [30]:
sil

[0.081241892350235698, 0.074084425106719226, 0.072839688812929348]

In [32]:
kmeans = KMeans(n_clusters=3, random_state=0).fit(data1)

In [33]:
labels=pd.DataFrame(kmeans.labels_)

In [36]:
labels[0].unique()

array([2, 0, 1], dtype=int64)

In [42]:
labels.columns=['label']

In [43]:
data1.head()

,V1 - I plan my expenses…,V2 - I always use new brands…,V3 - Weekends at home with family…,V4 - Buy more by impulse while shopping…,V5 - Watch online rather than TV shows,"V6 - Prefer reading, music rather than sports wctivities",V7 - Watch movies in first few days of release,V8 - I order for everyone while eating out,V9 - Some physical exercise everyday,"V10 - Prefer light, sober colours","V11 - I discuss my problem, rather than keeping them to myself",V12 - I like performing on a stage in front of a huge crowd,"V13 - At parties, I like mingling with new people rather than sticking to my close circle",V14 - Math Science were my favourite subjects in school,"V15 - When I see a new, interesting ad I most often end up buying the brand"
0,4,9,4,6,9,8,9,8,8,8,8,4,6,7,7
1,9,6,9,1,5,9,8,8,9,5,2,8,1,8,2
2,4,6,5,7,6,5,0,5,3,7,0,4,3,7,3
3,6,9,5,10,10,5,6,5,4,6,5,7,6,10,6
4,8,1,9,7,8,9,1,1,7,9,6,1,7,8,2

In [44]:
datafin=pd.concat([data1,labels],axis=1)

In [45]:
datafin.shape

(400, 16)

In [46]:
datafin.head()

,V1 - I plan my expenses…,V2 - I always use new brands…,V3 - Weekends at home with family…,V4 - Buy more by impulse while shopping…,V5 - Watch online rather than TV shows,"V6 - Prefer reading, music rather than sports wctivities",V7 - Watch movies in first few days of release,V8 - I order for everyone while eating out,V9 - Some physical exercise everyday,"V10 - Prefer light, sober colours","V11 - I discuss my problem, rather than keeping them to myself",V12 - I like performing on a stage in front of a huge crowd,"V13 - At parties, I like mingling with new people rather than sticking to my close circle",V14 - Math Science were my favourite subjects in school,"V15 - When I see a new, interesting ad I most often end up buying the brand",label
0,4,9,4,6,9,8,9,8,8,8,8,4,6,7,7,2
1,9,6,9,1,5,9,8,8,9,5,2,8,1,8,2,2
2,4,6,5,7,6,5,0,5,3,7,0,4,3,7,3,0
3,6,9,5,10,10,5,6,5,4,6,5,7,6,10,6,2
4,8,1,9,7,8,9,1,1,7,9,6,1,7,8,2,0

In [47]:
zero=datafin[datafin['label']==0]
one=datafin[datafin['label']==1]
two=datafin[datafin['label']==2]

In [48]:
zero.mean()

V1 - I plan my expenses…                                                                     5.127517
V2 - I always use new brands…                                                                4.691275
V3 - Weekends at home with family…                                                           6.483221
V4 - Buy more by impulse while shopping…                                                     6.248322
V5 - Watch online rather than TV shows                                                       7.550336
V6 - Prefer reading, music rather than sports wctivities                                     6.744966
V7 - Watch movies in first few days of release                                               4.348993
V8 - I order for everyone while eating out                                                   4.758389
V9 - Some physical exercise everyday                                                         2.550336
V10 - Prefer light, sober colours                                                            6.711409
V11 - I discuss my problem, rather than keeping them to myself                               3.899329
V12 - I like performing on a stage in front of a huge crowd                                  2.798658
V13 - At parties, I like mingling with new people rather than sticking to my close circle    3.919463
V14 - Math Science were my favourite subjects in school                                      6.335570
V15 - When I see a new, interesting ad I most often end up buying the brand                  4.617450
label                                                                                        0.000000
dtype: float64

In [52]:
one.mean()

V1 - I plan my expenses…                                                                     6.398058
V2 - I always use new brands…                                                                4.456311
V3 - Weekends at home with family…                                                           6.689320
V4 - Buy more by impulse while shopping…                                                     3.980583
V5 - Watch online rather than TV shows                                                       6.330097
V6 - Prefer reading, music rather than sports wctivities                                     2.708738
V7 - Watch movies in first few days of release                                               1.932039
V8 - I order for everyone while eating out                                                   5.233010
V9 - Some physical exercise everyday                                                         7.368932
V10 - Prefer light, sober colours                                                            6.601942
V11 - I discuss my problem, rather than keeping them to myself                               2.718447
V12 - I like performing on a stage in front of a huge crowd                                  3.029126
V13 - At parties, I like mingling with new people rather than sticking to my close circle    4.233010
V14 - Math Science were my favourite subjects in school                                      6.320388
V15 - When I see a new, interesting ad I most often end up buying the brand                  2.825243
label                                                                                        1.000000
dtype: float64

In [50]:
two.mean()

V1 - I plan my expenses…                                                                     6.385135
V2 - I always use new brands…                                                                6.263514
V3 - Weekends at home with family…                                                           5.945946
V4 - Buy more by impulse while shopping…                                                     6.425676
V5 - Watch online rather than TV shows                                                       7.608108
V6 - Prefer reading, music rather than sports wctivities                                     4.864865
V7 - Watch movies in first few days of release                                               6.182432
V8 - I order for everyone while eating out                                                   6.979730
V9 - Some physical exercise everyday                                                         6.540541
V10 - Prefer light, sober colours                                                            6.655405
V11 - I discuss my problem, rather than keeping them to myself                               4.756757
V12 - I like performing on a stage in front of a huge crowd                                  6.783784
V13 - At parties, I like mingling with new people rather than sticking to my close circle    6.297297
V14 - Math Science were my favourite subjects in school                                      6.810811
V15 - When I see a new, interesting ad I most often end up buying the brand                  6.033784
label                                                                                        2.000000
dtype: float64

sil1=[]
sumsquare1=[]
for i in range(3,6):
    kmeans = KMeans(n_clusters=i, random_state=0).fit(data2)
    sil1.append(silhouette_score(data2,kmeans.labels_))
    sumsquare1.append(kmeans.inertia_)

sil1

from sklearn.cluster import AgglomerativeClustering

sil2=[]
sumsquare2=[]
for i in range(3,6):
    kmeans = AgglomerativeClustering(n_clusters=i).fit(data1)
    sil2.append(silhouette_score(data1,kmeans.labels_))

sil2

In [61]:
one1=pd.DataFrame(one.mean())
two1=pd.DataFrame(two.mean())
zero1=pd.DataFrame(zero.mean())

In [64]:
one1.columns=['cluster 1']
two1.columns=['cluster 2']
zero1.columns=['cluster 0']

In [65]:
one1

                                                    cluster 1
V1 - I plan my expenses…                             6.398058
V2 - I always use new brands…                        4.456311
V3 - Weekends at home with family…                   6.689320
V4 - Buy more by impulse while shopping…             3.980583
V5 - Watch online rather than TV shows               6.330097
V6 - Prefer reading, music rather than sports w...   2.708738
V7 - Watch movies in first few days of release       1.932039
V8 - I order for everyone while eating out           5.233010
V9 - Some physical exercise everyday                 7.368932
V10 - Prefer light, sober colours                    6.601942
V11 - I discuss my problem, rather than keeping...   2.718447
V12 - I like performing on a stage in front of ...   3.029126
V13 - At parties, I like mingling with new peop...   4.233010
V14 - Math Science were my favourite subjects i...   6.320388
V15 - When I see a new, interesting ad I most o...   2.825243
label                                                1.000000

In [66]:
two1

                                                    cluster 2
V1 - I plan my expenses…                             6.385135
V2 - I always use new brands…                        6.263514
V3 - Weekends at home with family…                   5.945946
V4 - Buy more by impulse while shopping…             6.425676
V5 - Watch online rather than TV shows               7.608108
V6 - Prefer reading, music rather than sports w...   4.864865
V7 - Watch movies in first few days of release       6.182432
V8 - I order for everyone while eating out           6.979730
V9 - Some physical exercise everyday                 6.540541
V10 - Prefer light, sober colours                    6.655405
V11 - I discuss my problem, rather than keeping...   4.756757
V12 - I like performing on a stage in front of ...   6.783784
V13 - At parties, I like mingling with new peop...   6.297297
V14 - Math Science were my favourite subjects i...   6.810811
V15 - When I see a new, interesting ad I most o...   6.033784
label                                                2.000000

In [67]:
zero1

                                                    cluster 0
V1 - I plan my expenses…                             5.127517
V2 - I always use new brands…                        4.691275
V3 - Weekends at home with family…                   6.483221
V4 - Buy more by impulse while shopping…             6.248322
V5 - Watch online rather than TV shows               7.550336
V6 - Prefer reading, music rather than sports w...   6.744966
V7 - Watch movies in first few days of release       4.348993
V8 - I order for everyone while eating out           4.758389
V9 - Some physical exercise everyday                 2.550336
V10 - Prefer light, sober colours                    6.711409
V11 - I discuss my problem, rather than keeping...   3.899329
V12 - I like performing on a stage in front of ...   2.798658
V13 - At parties, I like mingling with new peop...   3.919463
V14 - Math Science were my favourite subjects i...   6.335570
V15 - When I see a new, interesting ad I most o...   4.617450
label                                                0.000000

In [55]:
one.shape

(103, 16)

In [56]:
two.shape

(148, 16)

In [58]:
zero.shape

(149, 16)

In [72]:
res=pd.concat([zero1.loc[:,'cluster 0'],one1.loc[:,'cluster 1'],two1.loc[:,'cluster 2']],axis=1)

In [102]:
res

,cluster 0,cluster 1,cluster 2
V1 - I plan my expenses…,5.127517,6.398058,6.385135
V2 - I always use new brands…,4.691275,4.456311,6.263514
V3 - Weekends at home with family…,6.483221,6.689320,5.945946
V4 - Buy more by impulse while shopping…,6.248322,3.980583,6.425676
V5 - Watch online rather than TV shows,7.550336,6.330097,7.608108
"V6 - Prefer reading, music rather than sports wctivities",6.744966,2.708738,4.864865
V7 - Watch movies in first few days of release,4.348993,1.932039,6.182432
V8 - I order for everyone while eating out,4.758389,5.233010,6.979730
V9 - Some physical exercise everyday,2.550336,7.368932,6.540541
"V10 - Prefer light, sober colours",6.711409,6.601942,6.655405
"V11 - I discuss my problem, rather than keeping them to myself",3.899329,2.718447,4.756757
V12 - I like performing on a stage in front of a huge crowd,2.798658,3.029126,6.783784
"V13 - At parties, I like mingling with new people rather than sticking to my close circle",3.919463,4.233010,6.297297
V14 - Math Science were my favourite subjects in school,6.335570,6.320388,6.810811
"V15 - When I see a new, interesting ad I most often end up buying the brand",4.617450,2.825243,6.033784

In [75]:
zero.to_excel('zero_cluster.xls')

In [76]:
one.to_excel('one_cluster.xls')

In [77]:
two.to_excel('two_cluster.xls')

In [79]:
res=res.iloc[0:-1,:]

In [80]:
res.to_excel('Mean_cluster.xls')

In [83]:
one_index=list(one.index)

In [86]:
zero_index=list(zero.index)

In [87]:
two_index=list(two.index)

In [89]:
len(zero_index)

149

In [90]:
len(two_index)

148

In [95]:
clus_one=data.iloc[one_index,:]
clus_zero=data.iloc[zero_index,:]
clus_two=data.iloc[two_index,:]

In [96]:
clus_one=clus_one.iloc[:,1:]

In [98]:
clus_zero=clus_zero.iloc[:,1:]
clus_two=clus_two.iloc[:,1:]

In [99]:
clus_zero

,V1 - I plan my expenses…,V2 - I always use new brands…,V3 - Weekends at home with family…,V4 - Buy more by impulse while shopping…,V5 - Watch online rather than TV shows,"V6 - Prefer reading, music rather than sports wctivities",V7 - Watch movies in first few days of release,V8 - I order for everyone while eating out,V9 - Some physical exercise everyday,"V10 - Prefer light, sober colours",...,Q2 - Mobile Phn Brand,Q3 - Favourite Soft Drink,Q4 - Newspaper read,Q5 - Shower Gel,Q6 - Hand sanitizers,Q7 - Face washes,Q8 - Hair conditioner,Q9 - Tea_Coffee,Q10 - Gender,Q11 - Occupation
2,4,6,5,7,6,5,0,5,3,7,...,HTC,Fruit flavour,Times of India,2,3,4,3,2,1,1
4,8,1,9,7,8,9,1,1,7,9,...,Others,Fruit flavour,Economic Times,2,3,2,2,1,1,1
7,10,2,8,1,10,6,2,0,1,8,...,Others,I do not consume soft drinks at all,Times of India,1,1,4,1,2,1,1
8,5,0,3,0,10,6,3,6,0,5,...,Others,Fruit flavour,Business Standards,2,4,4,3,2,1,1
10,4,3,5,6,9,10,4,1,1,6,...,Others,White/ Colourless,The Telegraph,2,2,4,3,1,2,1
11,0,7,3,7,10,10,0,9,0,4,...,Others,Cola,Times of India,4,2,4,4,2,2,1
15,8,6,8,7,8,8,4,3,5,2,...,Samsung,Fruit flavour,Economic Times,3,2,4,3,1,2,1
16,9,0,5,0,0,10,10,10,0,10,...,Samsung,Cola,Times of India,1,1,1,3,2,1,1
23,4,0,6,10,10,7,0,10,4,4,...,Apple,Cola,The Telegraph,2,3,3,3,2,1,1
26,9,10,8,4,10,10,1,9,3,10,...,HTC,Orange,Times of India,3,4,4,2,1,1,1
31,3,9,8,9,10,10,9,8,2,9,...,Others,White/ Colourless,Times of India,1,3,4,4,1,1,1
32,3,8,10,9,0,8,0,5,1,9,...,HTC,Cola,Times of India,4,2,1,1,1,2,1
34,6,7,1,8,5,7,2,6,3,7,...,Others,Cola,Times of India,4,4,4,2,2,1,2
35,2,3,2,6,10,6,7,2,3,5,...,Others,Cola,Times of India,2,1,4,2,1,1,2
36,1,7,8,8,6,6,8,6,4,6,...,Apple,Orange,Times of India,4,2,4,2,1,2,1
52,5,2,5,8,5,8,4,1,2,10,...,Apple,Cola,Times of India,4,4,4,3,1,2,1
53,3,7,8,5,9,5,5,4,5,2,...,Others,Cola,The Telegraph,4,2,4,4,2,2,1
67,2,2,6,10,10,0,5,9,3,10,...,Samsung,Cola,Business Standards,3,1,4,3,1,1,1
68,6,2,2,9,9,5,3,9,3,8,...,HTC,Cola,Times of India,4,3,4,3,2,2,1
70,7,4,9,8,6,6,5,8,0,10,...,Samsung,Cola,Economic Times,4,3,4,3,1,2,1
71,5,0,5,8,9,8,5,5,10,7,...,Samsung,Cola,Times of India,4,4,4,3,1,2,1
73,1,5,8,8,10,6,5,8,2,10,...,Apple,Cola,Times of India,4,4,4,3,1,2,1
83,6,3,3,4,6,6,3,6,1,7,...,Samsung,White/ Colourless,Economic Times,1,4,4,3,1,2,1
84,1,4,8,9,6,2,7,5,1,7,...,Others,Cola,The Telegraph,3,4,4,3,1,1,1
86,2,1,0,7,4,9,1,6,4,7,...,Samsung,Cola,The Telegraph,4,4,4,4,1,2,1
87,8,4,9,6,9,8,3,7,5,9,...,HTC,I do not consume soft drinks at all,Times of India,4,3,4,3,2,2,1
88,3,5,7,3,6,4,9,6,3,5,...,Others,Cola,Economic Times,3,4,4,4,2,1,1
90,4,9,8,8,9,7,10,3,1,8,...,Others,Cola,Times of India,2,2,4,2,2,1,1
93,4,2,5,4,10,2,4,7,3,9,...,Others,Cola,Economic Times,1,4,2,3,1,1,1
98,2,3,9,3,2,8,3,4,4,1,...,HTC,Cola,The Hindu,2,4,4,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333,5,5,5,5,5,5,5,5,5,5,...,Apple,Cola,Economic Times,4,4,4,2,2,1,1
337,7,3,8,7,9,4,7,6,3,6,...,Others,Cola,Economic Times,2,2,3,2,1,1,1
338,8,7,9,0,8,9,7,9,0,5,...,Others,Cola,Times of India,3,2,4,3,2,1,1
341,6,7,9,8,10,5,7,5,1,4,...,Samsung,Cola,The Hindu,4,3,4,2,1,1,1
344,6,5,6,7,5,7,0,9,4,1,...,Others,Orange,The Telegraph,4,2,2,2,1,1,1
345,2,3,7,8,6,10,9,3,2,2,...,Apple,I do not consume soft drinks at all,The Hindu,2,2,2,3,2,1,1
347,7,8,9,7,9,10,10,5,1,9,...,Apple,I do not consume soft drinks at all,Economic Times,4,3,4,4,2,2,2
348,8,5,10,9,10,10,10,2,0,9,...,Others,Fruit flavour,The Hindu,1,4,4,2,2,1,1
353,4,3,7,7,6,10,1,1,6,10,...,Sony,White/ Colourless,Times of India,4,2,4,3,2,2,1
354,6,2,3,4,1,8,4,1,1,4,...,Others,Cola,Times of India,4,2,4,2,2,1,1
358,1,6,6,3,10,7,7,7,2,7,...,Samsung,White/ Colourless,The Telegraph,1,2,4,3,2,1,1
359,7,6,2,7,10,10,0,0,0,0,...,Nokia,I do not consume soft drinks at all,The Hindu,3,3,4,2,2,2,1
360,10,3,5,5,1,7,2,3,1,5,...,Others,White/ Colourless,Times of India,3,2,4,3,2,2,1
361,1,6,3,7,10,3,2,3,5,1,...,Apple,Cola,The Hindu,3,3,4,1,2,2,1
362,5,7,7,3,8,5,10,9,2,7,...,Others,Cola,Mint,2,2,4,4,2,1,1
366,8,6,8,7,7,3,0,8,2,7,...,Others,I do not consume soft drinks at all,Mint,4,2,4,3,2,1,1
369,2,7,7,8,9,8,6,2,3,6,...,Apple,Cola,Times of India,4,4,4,4,2,1,1
372,9,5,8,8,8,9,8,8,3,8,...,Others,Cola,Economic Times,4,2,4,3,2,2,1
375,2,6,3,9,9,4,0,8,7,3,...,Others,I do not consume soft drinks at all,Economic Times,3,2,4,3,2,1,1
377,2,3,8,10,7,5,9,9,1,3,...,Nokia,Cola,Times of India,4,3,4,3,2,1,1
379,1,6,4,9,5,3,8,8,3,7,...,Nokia,Cola,Times of India,4,3,4,3,2,1,1
383,3,5,5,7,10,5,3,3,5,7,...,Others,I do not consume soft drinks at all,The Hindu,1,4,4,3,2,1,1
384,3,5,6,0,8,4,8,5,2,5,...,Apple,Cola,The Hindu,2,2,3,4,2,1,1
387,1,1,8,1,8,5,0,0,0,10,...,Others,Cola,Times of India,3,4,4,3,1,1,2
390,4,5,5,8,9,8,5,6,4,4,...,Others,Cola,Times of India,2,3,4,3,1,1,1
394,8,5,10,3,9,3,5,4,0,0,...,Samsung,Fruit flavour,The Hindu,1,4,4,2,1,1,1
396,4,0,10,2,10,10,0,0,0,10,...,Sony,Cola,Times of India,1,2,2,1,2,1,1
397,9,6,8,6,9,8,3,3,3,8,...,Others,Cola,The Hindustan Times,2,4,4,3,1,1,1
398,3,6,2,10,10,7,7,0,7,6,...,Others,Cola,Times of India,4,4,4,3,2,2,1
399,6,3,8,6,10,4,0,3,2,7,...,Others,Cola,Times of India,3,2,4,3,1,1,1

In [100]:
clus_two

,V1 - I plan my expenses…,V2 - I always use new brands…,V3 - Weekends at home with family…,V4 - Buy more by impulse while shopping…,V5 - Watch online rather than TV shows,"V6 - Prefer reading, music rather than sports wctivities",V7 - Watch movies in first few days of release,V8 - I order for everyone while eating out,V9 - Some physical exercise everyday,"V10 - Prefer light, sober colours",...,Q2 - Mobile Phn Brand,Q3 - Favourite Soft Drink,Q4 - Newspaper read,Q5 - Shower Gel,Q6 - Hand sanitizers,Q7 - Face washes,Q8 - Hair conditioner,Q9 - Tea_Coffee,Q10 - Gender,Q11 - Occupation
0,4,9,4,6,9,8,9,8,8,8,...,Samsung,Cola,Economic Times,3,4,4,3,1,1,1
1,9,6,9,1,5,9,8,8,9,5,...,Others,Orange,The Hindu,1,2,2,3,1,1,1
3,6,9,5,10,10,5,6,5,4,6,...,Others,I do not consume soft drinks at all,The Hindu,3,3,4,3,1,2,1
5,3,7,5,6,10,10,2,0,10,10,...,Apple,Cola,Mint,4,4,4,1,2,1,1
12,0,5,0,2,9,4,9,6,3,7,...,Apple,Fruit flavour,Economic Times,4,3,4,3,2,1,1
13,7,7,3,3,10,5,3,3,7,8,...,Others,I do not consume soft drinks at all,Mint,3,4,4,3,1,1,1
18,7,8,6,9,7,1,9,7,8,10,...,LG,Cola,Mint,2,2,3,3,2,1,1
19,0,2,3,7,8,5,6,9,3,5,...,Apple,White/ Colourless,The Hindu,4,4,4,3,2,1,1
20,7,2,5,7,10,3,5,9,3,8,...,Apple,Fruit flavour,"Regional Newspapers like Sanmarg, Jansatta, An...",4,4,4,3,1,2,2
21,9,10,5,1,10,1,0,9,8,8,...,Nokia,Fruit flavour,Economic Times,2,4,4,3,1,1,1
22,2,7,3,1,7,5,3,7,5,8,...,Others,Cola,Times of India,1,4,3,1,2,1,1
24,6,5,9,7,7,9,8,8,8,8,...,Samsung,Orange,The Telegraph,2,4,3,3,1,1,1
28,7,2,8,10,9,1,9,7,10,5,...,Others,I do not consume soft drinks at all,Times of India,4,3,4,4,2,2,2
33,9,6,8,7,6,5,7,6,5,8,...,Samsung,Cola,Economic Times,2,4,2,2,1,1,1
38,8,8,7,0,9,5,5,5,8,9,...,Others,I do not consume soft drinks at all,The Telegraph,1,1,4,4,1,1,1
39,4,4,3,2,2,4,8,8,7,9,...,Others,Cola,Times of India,4,2,4,3,1,1,1
40,4,9,10,9,10,2,3,9,5,9,...,Apple,Orange,Economic Times,3,2,4,2,2,1,1
44,4,7,8,10,10,0,9,9,10,10,...,Apple,I do not consume soft drinks at all,The Hindu,2,4,4,2,2,1,1
46,7,8,5,10,7,9,8,10,10,7,...,Samsung,White/ Colourless,Times of India,3,4,4,4,1,2,2
47,10,9,8,6,8,9,8,7,9,8,...,Others,Cola,Times of India,3,3,3,3,1,1,1
48,7,10,10,7,10,5,7,10,2,5,...,Others,I do not consume soft drinks at all,The Hindu,4,4,4,2,2,1,1
50,2,8,1,10,5,3,3,1,8,10,...,Apple,Cola,The Telegraph,4,4,4,3,2,2,1
51,6,2,3,7,10,2,5,7,8,9,...,Others,Orange,Times of India,1,3,4,2,2,2,1
54,10,5,7,3,8,5,8,7,6,8,...,Others,White/ Colourless,Times of India,3,4,4,3,1,1,1
55,8,5,5,10,5,0,0,5,0,5,...,Samsung,Cola,Economic Times,2,3,4,4,1,2,1
56,7,4,8,10,9,6,4,10,10,5,...,Samsung,Cola,Economic Times,4,3,4,3,1,2,1
57,8,5,5,3,9,5,7,10,10,5,...,Samsung,Orange,Economic Times,4,4,4,3,2,2,1
58,7,5,2,1,1,1,8,6,7,5,...,HTC,Cola,Economic Times,2,2,4,3,1,1,1
60,10,0,5,0,10,5,10,8,5,5,...,Samsung,White/ Colourless,Times of India,2,4,4,3,1,1,1
61,8,7,6,4,9,9,5,10,7,0,...,Others,Fruit flavour,Times of India,2,4,4,3,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,9,7,9,4,8,5,9,10,8,9,...,Others,Fruit flavour,The Hindu,3,4,4,3,2,2,1
293,8,7,5,8,10,2,10,8,7,2,...,Others,Cola,Times of India,2,4,4,1,2,1,1
296,7,6,10,8,9,2,2,5,10,9,...,Others,I do not consume soft drinks at all,Economic Times,4,2,4,1,2,2,1
300,8,6,5,7,10,8,2,1,4,7,...,Apple,Fruit flavour,Economic Times,4,4,4,3,1,2,1
312,8,5,4,4,8,4,9,7,8,8,...,Others,White/ Colourless,The Telegraph,2,2,2,2,2,1,1
315,4,6,3,0,8,0,9,9,5,3,...,Others,Cola,The Hindu,4,4,4,2,1,1,1
316,1,8,0,10,5,8,0,9,4,2,...,Others,Cola,Economic Times,1,4,1,1,1,1,1
317,7,5,7,8,9,10,6,1,2,3,...,Others,White/ Colourless,Times of India,1,4,2,1,2,1,1
318,9,4,3,4,8,2,9,9,8,3,...,Apple,White/ Colourless,Economic Times,4,4,4,3,2,1,1
325,8,4,3,6,5,3,4,6,6,5,...,Apple,Fruit flavour,Business Standards,4,3,4,4,2,2,1
331,3,8,9,7,6,8,7,2,3,2,...,Samsung,Orange,Times of India,4,3,4,3,2,2,1
336,8,9,7,3,9,4,8,10,8,3,...,HTC,Cola,The Hindu,3,4,2,4,1,1,1
339,9,4,9,9,7,6,6,5,8,2,...,Apple,Cola,Times of India,2,2,4,3,2,2,1
340,8,9,8,3,3,3,8,8,8,9,...,Samsung,White/ Colourless,The Telegraph,2,4,4,3,2,2,1
342,7,7,5,10,2,5,4,7,9,8,...,Apple,I do not consume soft drinks at all,The Hindustan Times,4,4,4,3,1,2,1
343,5,9,9,7,7,5,3,9,10,5,...,Apple,Fruit flavour,The Hindu,3,3,4,3,1,1,1
349,7,7,8,7,8,7,8,8,8,8,...,Others,I do not consume soft drinks at all,Economic Times,4,2,2,4,2,1,1
350,10,6,5,0,7,10,7,4,4,5,...,Others,Cola,Economic Times,1,2,1,1,1,1,1
355,7,8,3,7,7,5,6,5,3,6,...,Others,Fruit flavour,Times of India,3,4,4,2,2,1,1
356,7,5,3,7,4,3,6,8,4,5,...,Apple,Cola,The Hindu,4,4,4,4,1,1,1
357,6,7,3,10,7,7,1,8,5,5,...,Apple,Cola,Economic Times,3,1,4,3,2,2,1
363,8,8,8,4,9,4,4,4,9,7,...,Others,Fruit flavour,Economic Times,4,2,4,3,2,1,1
364,0,2,5,7,8,0,7,0,8,0,...,Others,Cola,The Hindustan Times,4,2,4,3,1,1,1
367,5,8,8,9,10,5,2,5,7,9,...,Micromax,Cola,The Hindu,3,2,2,2,1,1,1
368,7,6,6,6,9,4,4,6,4,7,...,Sony,Fruit flavour,Economic Times,4,3,4,4,2,2,1
370,6,6,4,8,8,5,5,7,6,7,...,Others,Cola,The Hindu,2,3,4,3,2,2,1
381,6,6,5,5,9,7,8,7,7,7,...,Samsung,Cola,Times of India,3,4,4,4,2,1,1
391,3,7,2,9,10,0,10,5,5,1,...,Others,Cola,The Hindu,3,4,4,4,2,1,1
393,6,5,5,3,9,2,8,5,7,2,...,Others,Cola,The Hindustan Times,3,4,4,3,2,1,1
395,8,8,10,5,2,8,9,2,10,7,...,Samsung,Orange,Times of India,3,2,4,3,1,1,3

In [101]:
clus_zero.to_excel('clus_zero.xls')
clus_one.to_excel('clus_one.xls')
clus_two.to_excel('clus_two.xls')